Add NodeReal as infra providor
aptos-foundation/ecosystem-projects pull request #10
Opened 2022-11-17 05:48 UTC by nodereal-keeper

2022-11-20 03:20 UTC, CapCap commented
Please make sure to keep it alphabetical (and there is some change at the end of the file, please undo that one)

Thanks!

2022-11-21 01:25 UTC, CapCap requested changes
please see above note, thanks!

2022-11-21 05:16 UTC, nodereal-keeper commented
updated! please review again!

2022-11-22 19:56 UTC, AustinOutside approved these changes

2022-11-22 22:12 UTC, merged